--- 
- :name: hpricot
- :name: bluecloth
  :version: "> 2.0.0"
- :name: fastercsv
- :name: pdf-writer
- :name: rack
  :version: ">= 1.0.0"
- :name: system-timer
- :name: capistrano
- :name: capistrano-ext
- :name: rails
  :version: 2.3.3
