--- 
- :name: bluecloth
  :version: "> 2.0.0"
- :name: fastercsv
  :version: = 1.2.3
- :name: pdf-writer
- :name: rack
  :version: ">= 1.0.0"
- :name: system_timer
- :name: googlecharts
- :name: capistrano
- :name: capistrano-ext
- :name: rails
  :version: 2.3.3
